/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/demande` | `/demande`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/documents` | `/documents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/rendez-vous` | `/rendez-vous`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/demande` | `/demande`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/documents` | `/documents`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/rendez-vous` | `/rendez-vous`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signin${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/demande${`?${string}` | `#${string}` | ''}` | `/demande${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/documents${`?${string}` | `#${string}` | ''}` | `/documents${`?${string}` | `#${string}` | ''}` | `${'/(client)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/rendez-vous${`?${string}` | `#${string}` | ''}` | `/rendez-vous${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/demande` | `/demande`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/documents` | `/documents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/rendez-vous` | `/rendez-vous`; params?: Router.UnknownInputParams; };
    }
  }
}
